// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using posss;

namespace posss.Migrations
{
    [DbContext(typeof(Model))]
    partial class ModelModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("ProduktTransakcja", b =>
                {
                    b.Property<int>("produktsProduktId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("transaksTransakcjaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("produktsProduktId", "transaksTransakcjaId");

                    b.HasIndex("transaksTransakcjaId");

                    b.ToTable("ProduktTransakcja");
                });

            modelBuilder.Entity("posss.Produkt", b =>
                {
                    b.Property<int>("ProduktId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cena")
                        .HasColumnType("REAL");

                    b.Property<string>("KodKreskowy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.HasKey("ProduktId");

                    b.ToTable("Produkty");
                });

            modelBuilder.Entity("posss.Transakcja", b =>
                {
                    b.Property<int>("TransakcjaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("ilosc")
                        .HasColumnType("TEXT");

                    b.Property<string>("typ")
                        .HasColumnType("TEXT");

                    b.HasKey("TransakcjaId");

                    b.ToTable("Transakcje");
                });

            modelBuilder.Entity("ProduktTransakcja", b =>
                {
                    b.HasOne("posss.Produkt", null)
                        .WithMany()
                        .HasForeignKey("produktsProduktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("posss.Transakcja", null)
                        .WithMany()
                        .HasForeignKey("transaksTransakcjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
